"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import Sidebar from "./Sidebar";
import OverviewPanel from "./OverviewPanel";
import SignalsPanel from "./SignalsPanel";
import AutomationsPanel from "./AutomationsPanel";
import { sidebarItems, type TabKey } from "./data";

const panels: Record<TabKey, React.ComponentType> = {
  overview: OverviewPanel,
  signals: SignalsPanel,
  automations: AutomationsPanel,
};

const titles: Record<TabKey, { title: string; sub: string }> = {
  overview: {
    title: "Overview",
    sub: "Everything flowing through the workspace right now.",
  },
  signals: {
    title: "Signals",
    sub: "Insight objects generated by the model, ranked by confidence.",
  },
  automations: {
    title: "Automations",
    sub: "What Xai is doing on your behalf, without a prompt.",
  },
};

export default function DashboardPreview() {
  const [tab, setTab] = useState<TabKey>("overview");
  const Panel = panels[tab];

  return (
    <section id="dashboard" className="relative bg-base px-6 py-28 md:px-10">
      <div className="mx-auto max-w-[1160px]">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-80px" }}
          transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
          className="mb-10 flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end"
        >
          <div>
            <span className="font-mono text-[11px] uppercase tracking-[0.18em] text-faint">
              Intelligence dashboard
            </span>
            <h2 className="mt-3 font-display text-[9vw] font-medium leading-[0.98] tracking-tight text-primary sm:text-[3.4vw]">
              The workspace, not the pitch.
            </h2>
          </div>
          <p className="max-w-[320px] text-[14px] leading-relaxed text-muted">
            A live look at how ingestion, analysis, and insight sit side by
            side once the data has been structured.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 28, scale: 0.985 }}
          whileInView={{ opacity: 1, y: 0, scale: 1 }}
          viewport={{ once: true, margin: "-60px" }}
          transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          className="overflow-hidden rounded-2xl border border-border-soft bg-panel shadow-[0_40px_120px_-40px_rgba(108,124,255,0.25)]"
        >
          <div className="flex items-center gap-2 border-b border-border-hair px-4 py-3">
            <span className="h-2.5 w-2.5 rounded-full bg-border-soft" />
            <span className="h-2.5 w-2.5 rounded-full bg-border-soft" />
            <span className="h-2.5 w-2.5 rounded-full bg-border-soft" />
            <span className="ml-3 font-mono text-[11px] text-faint">
              workspace.xai.app/{tab}
            </span>
          </div>

          <div className="flex min-h-[520px] flex-col md:flex-row">
            <Sidebar active={tab} onChange={setTab} />

            <div className="flex-1 overflow-hidden px-5 py-6 md:px-7 md:py-7">
              <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
                <div>
                  <h3 className="font-display text-[19px] font-medium text-primary">
                    {titles[tab].title}
                  </h3>
                  <p className="mt-0.5 text-[12.5px] text-muted">
                    {titles[tab].sub}
                  </p>
                </div>
                <div className="flex gap-1.5 rounded-full border border-border-hair p-1 md:hidden">
                  {sidebarItems.map((s) => (
                    <button
                      key={s.key}
                      onClick={() => setTab(s.key)}
                      className={`rounded-full px-3 py-1 font-mono text-[10.5px] uppercase ${
                        tab === s.key
                          ? "bg-panel-alt text-primary"
                          : "text-faint"
                      }`}
                    >
                      {s.label}
                    </button>
                  ))}
                </div>
              </div>

              <AnimatePresence mode="wait">
                <motion.div
                  key={tab}
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.25, ease: [0.16, 1, 0.3, 1] }}
                >
                  <Panel />
                </motion.div>
              </AnimatePresence>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
